version: "3.2"

services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        environment:
            - discovery.type=single-node
        networks:
            - newsroom

    redis:
        image: redis:alpine
        networks:
            - newsroom

    mongo:
        image: mongo:4
        networks:
            - newsroom

    server:
        build: ./server
        ports:
            - "5050:5050"
            - "5150:5150"
        networks:
            - newsroom
        volumes:
            - ./dump:/opt/newsroom/dump
            - ./client/dist:/opt/client/dist
        depends_on:
            - elastic
            - redis
            - mongo
        environment:
            - WEB_CONCURRENCY=2
            - WEBPACK_MANIFEST_PATH=/opt/client/dist/manifest.json
            - WEBPACK_ASSETS_URL=http://localhost:8080
            - MONGO_URI=mongodb://mongo/newsroom
            - CONTENTAPI_MONGO_URI=mongodb://mongo:27017/newsroom
            - ELASTICSEARCH_URL=http://elastic:9200
            - ELASTICSEARCH_INDEX=newsroom
            - CELERY_BROKER_URL=redis://redis:6379/1
            - REDIS_URL=redis://redis:6379/1
            - DEFAULT_TIMEZONE=Europe/Prague
            - SECRET_KEY=newsroom
            - NEWSROOM_DEBUG=true

networks:
    newsroom:
        driver: bridge
