name: "CI"

on:
  [ push, pull_request ]

jobs:

  server:
    strategy:
      matrix:
        python-version: ['3.10']
    uses: ./.github/workflows/server.yml
    with: 
        python-version: ${{ matrix.python-version }}

  pytest:
    strategy:
      matrix:
        python-version: ['3.10']
    uses: ./.github/workflows/pytest.yml
    with:
        python-version: ${{ matrix.python-version }}

  behave:
    strategy:
      matrix:
        python-version: ['3.10']
    uses: ./.github/workflows/behave.yml
    with:
        python-version: ${{ matrix.python-version }}

  client:
    strategy:
      matrix:
        node-version: ['14', '18', '20', 'lts/*']
    uses: ./.github/workflows/client.yml
    with:
        node-version: ${{ matrix.node-version }}